spring:
  datasource:
    # for test
    url: jdbc:postgresql://localhost:5432/toy_recruit_local
    username: postgres
    password: seongha123

  jpa:
    hibernate:
      ddl-auto: create-drop # for test
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true # for test
    show-sql: true # for test